<a href="https://colab.research.google.com/github/Anushanga2001/LLM_model/blob/model/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Next word predictions according to the RNN**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
# When doing the word predictions , we have to use indexing for do predictions
# And also need to identify the size of the array

In [ ]:
from os import read
with open("/content/Cricket is a popular sport with a l.txt", 'r', encoding='utf-8') as f:
  text = f.read()

In [ ]:
text
# get the result of text

'### Cricket: A Brief Overview\n\nCricket is a bat-and-ball game that has captivated millions of fans worldwide. Originating in England during the 16th century, it has evolved into a global sport with a rich history and diverse forms of play. Here’s an exploration of the game, its structure, and its cultural significance.\n\n#### **The Game Structure**\n\nCricket is typically played between two teams of eleven players each. The game can be divided into several formats, with the most popular being:\n\n1. **Test Cricket:** The longest format, lasting up to five days, where each team plays two innings. Test cricket is known for its strategic depth and endurance.\n2. **One Day Internationals (ODIs):** Limited to 50 overs per side, ODIs are faster-paced than Test matches and usually completed in a single day.\n3. **Twenty20 (T20) Cricket:** The shortest format, with each team playing 20 overs. T20 cricket is known for its explosive action and has significantly boosted the sport\'s popularit

In [ ]:
filter = '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'
# if want to get the indexes for the '\n' kind of words, that time have
# to use the filter option

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()

In [ ]:
tokenizer.fit_on_texts([text])

In [ ]:
tokenizer.get_config()
# get index for each and every word

{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"cricket": 12, "a": 15, "brief": 1, "overview": 1, "is": 7, "bat": 1, "and": 24, "ball": 5, "game": 6, "that": 3, "has": 4, "captivated": 1, "millions": 2, "of": 15, "fans": 2, "worldwide": 1, "originating": 1, "in": 6, "england": 3, "during": 1, "the": 39, "16th": 1, "century": 1, "it": 4, "evolved": 2, "into": 2, "global": 3, "sport": 4, "with": 5, "rich": 2, "history": 1, "diverse": 2, "forms": 1, "play": 2, "here\\u2019s": 1, "an": 1, "exploration": 1, "its": 7, "structure": 2, "cultural": 3, "significance": 2, "typically": 1, "played": 1, "between": 3, "two": 2, "teams": 1, "eleven": 1, "players": 3, "each": 3, "can": 3, "be": 3, "divided": 1, "several": 1, "formats": 2, "most": 2, "popular": 1, "being": 2, "1": 1, "test": 6, "longest": 1, "format": 2, "lasting": 1, "up": 1, "to": 9, "five": 1, "day

In [ ]:
tokenizer.index_word
# word by word index

{1: 'the',
 2: 'and',
 3: 'a',
 4: 'of',
 5: 'cricket',
 6: 'to',
 7: 'is',
 8: 'its',
 9: 'game',
 10: 'in',
 11: 'test',
 12: 'for',
 13: 'runs',
 14: 'ball',
 15: 'with',
 16: 'or',
 17: 'has',
 18: 'it',
 19: 'sport',
 20: 'team',
 21: 'known',
 22: 't20',
 23: 'that',
 24: 'england',
 25: 'global',
 26: 'cultural',
 27: 'between',
 28: 'players',
 29: 'each',
 30: 'can',
 31: 'be',
 32: 'day',
 33: 'odis',
 34: 'matches',
 35: 'by',
 36: 'hitting',
 37: 'india',
 38: 'west',
 39: 'indies',
 40: 'as',
 41: 'have',
 42: 'millions',
 43: 'fans',
 44: 'evolved',
 45: 'into',
 46: 'rich',
 47: 'diverse',
 48: 'play',
 49: 'structure',
 50: 'significance',
 51: 'two',
 52: 'formats',
 53: 'most',
 54: 'being',
 55: 'format',
 56: 'overs',
 57: 'than',
 58: 'batting',
 59: 'around',
 60: 'who',
 61: 'fielding',
 62: 'from',
 63: 'scoring',
 64: 'batsmen',
 65: 'if',
 66: 'before',
 67: 'boundary',
 68: 'countries',
 69: 'australia',
 70: 'people',
 71: 'league',
 72: 'these',
 73: 'uniqu

In [ ]:
# To get the sentences sequencially display with the indexes
input_sequences = []
for sentence in text.split('\n'):
  # print(sentence)
  token_list = tokenizer.texts_to_sequences([sentence])[0]
  # print(token_list)
  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    input_sequences.append(n_gram_sequence)

In [ ]:
input_sequences[:5]
# Look at the pattern one after next index

[[5, 3], [5, 3, 76], [5, 3, 76, 77], [5, 7], [5, 7, 3]]

In [ ]:
# get the meximun length of the input_sequences
max_sequence_len = max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

In [ ]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  5,  3, 76], dtype=int32)

In [ ]:
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [ ]:
# x varible index check in 2nd element
x[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 5, 3], dtype=int32)

In [ ]:
y[1]

76

In [ ]:
# Do the one-hot encoding for the y variable
num_classes = len(tokenizer.word_index) + 1
num_classes

262

In [ ]:
y = tf.keras.utils.to_categorical(y, num_classes=num_classes)

In [ ]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

Train the model

In [ ]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_sequence_len-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# train the model
model.fit(x, y, epochs=100)
# meaning of epochs is, train the model 100 times

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.0536 - loss: 5.5642
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.0930 - loss: 5.3687
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.0880 - loss: 5.0834
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 77ms/step - accuracy: 0.0801 - loss: 5.0308
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.0706 - loss: 5.0581
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.0686 - loss: 5.1079
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.0758 - loss: 4.9778
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.0678 - loss: 4.9624
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.0833 - loss: 4.9297
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.0904 - loss: 4.8162
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.0810 - loss: 4.8526
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step

In [ ]:
input_text = "Cricket is a popular sport with a"

In [ ]:
token_list = tokenizer.texts_to_sequences([input_text])[0]
print(token_list)

[5, 7, 3, 96, 19, 15, 3]


In [ ]:
token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
print(token_list)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5
   7  3 96 19 15  3]]


In [ ]:
#  Get the predictin word index
predicted = np.argmax(model.predict(token_list), axis=-1)
print(predicted)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 305ms/step
[26]


In [ ]:
# get the word of that particular index
for word, index in tokenizer.word_index.items():
  if index == predicted:
    print(word)

cultural


In [ ]:
# predict the next 6 word of a particular sentence
input_text = "Cricket is a popular sport with a"
for i in range(6):
  token_list = tokenizer.texts_to_sequences([input_text])[0]
  token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
  predicted = np.argmax(model.predict(token_list), axis=-1)
  for word, index in tokenizer.word_index.items():
    if index == predicted:
      input_text += " " + word
      print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Cricket is a popular sport with a cultural
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Cricket is a popular sport with a cultural phenomenon
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Cricket is a popular sport with a cultural phenomenon in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
Cricket is a popular sport with a cultural phenomenon in many
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Cricket is a popular sport with a cultural phenomenon in many countries
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Cricket is a popular sport with a cultural phenomenon in many countries particularly
